apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  namespace: monitoring-elk
  labels:
    app: elasticsearch
    stack: logging
spec:
  # storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G